// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CommonLayer: typeof import('./src/components/commonLayer/CommonLayer.vue')['default']
    ContrastPlane: typeof import('./src/components/3DSimulation/ContrastPlane.vue')['default']
    CylinderYouShi: typeof import('./src/components/travalInfo/CylinderYouShi.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxButton: typeof import('element-plus/es')['ElCheckboxButton']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FloodAnalysis: typeof import('./src/components/3DSimulation/FloodAnalysis.vue')['default']
    FocusProvince: typeof import('./src/components/travalInfo/FocusProvince.vue')['default']
    HeadTitle: typeof import('./src/components/HeadTitle.vue')['default']
    OverView: typeof import('./src/components/travalInfo/OverView.vue')['default']
    Photo: typeof import('./src/components/photo/Photo.vue')['default']
    Polyline: typeof import('./src/components/commonLayer/Polyline.vue')['default']
    Province: typeof import('./src/components/commonLayer/Province.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThreeSimulation: typeof import('./src/components/3DSimulation/ThreeSimulation.vue')['default']
    TravalInfo: typeof import('./src/components/travalInfo/TravalInfo.vue')['default']
    Video: typeof import('./src/components/video/Video.vue')['default']
    VideoCamera: typeof import('./src/components/video/VideoCamera.vue')['default']
    VideoMonitor: typeof import('./src/components/video/VideoMonitor.vue')['default']
  }
}
